# Generated by Django 4.0.3 on 2022-03-29 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EmailApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretkey',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
