# Generated by Django 4.0.3 on 2022-03-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailApp', '0002_alter_secretkey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretkey',
            name='projectname',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
